5 2pt setup reducer for fetching doctors
muneebulrehman/doctors-appointment-frontend pull request #6
Opened 2022-07-14 14:36 UTC by muneebulrehman

action/reducers for fetching a single doctor and a list of doctors

2022-07-14 19:52 UTC, damdafayton requested changes

2022-07-14 19:52 UTC, damdafayton commented on src/features/doctor/doctorSlice.js
> +      state.error = action.error.message;
Maybe double check this? I am not sure if error message is handled on api.

2022-07-14 19:52 UTC, damdafayton commented on src/App.js
> +        <DoctorView />
Maybe its better to set this inside Route for '/' ?

2022-07-15 00:00 UTC, muneebulrehman commented on src/App.js
> +        <DoctorView />
It was just a dummy file to check whether the action/reducers were working.

2022-07-15 00:07 UTC, muneebulrehman commented on src/features/doctor/doctorSlice.js
> +      state.error = action.error.message;
Yeah, that is right. Not handling the errors.

2022-07-15 00:20 UTC, merged